

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: pricepulse_app
        volumes:
            - .:/var/www
        depends_on:
            - db

    web:
        image: nginx:alpine
        container_name: pricepulse_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: pricepulse_db
        environment:
            MYSQL_DATABASE: pricepulse
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
